### ISSUE TITLE
Correctly handle Certificates

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#102]
**User story**

In #72 we've added structures to the machine actuator and to bootstrap scripts allowing custom Certificates to be installed.

However, it isn't possible to provide certificates and it's not documented how this works.

To make this feature easier it is important to define how certificates should be provided. An idea is to add appropriate structures to the Cluster providerConfig, such as:

```yaml
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: $CLUSTER_NAME
  namespace: $NAMESPACE
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/12"]
        pods:
            cidrBlocks: ["10.244.0.0/16"]
        serviceDomain: "cluster.local"
    providerConfig:
      value:
        apiVersion: "digitaloceanproviderconfig/v1alpha1"
        kind: "DigitaloceanClusterProviderConfig"
        certificates:
          ca-cert: <base64-encoded-ca-cert>
          ca-key: <base64-encoded-ca-key>
```

If certificates are not provided by the operator, we have two options:

1. Let kubeadm generate certificates automatically (this what we currently do),
1. Generate certificates manually, on operator machine, and provide them to cluster like custom certificates

The second approach would allow us to refactor the GetKubeConfig function to build Kubeconfig file based on certificates, rather than downloading it over SSH. This would improve stability and speed by a large margin.

[For example, the similar approach is used by AWS provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/935415f97d96701572874d12190e217a175b485b/cloud/aws/actuators/cluster/actuator.go#L218-L259).

**Acceptance criteria**

- [ ] User can specify custom certificates to be used by the cluster
- [ ] Potentially, certificate generation is handled by us rather than by kubeadm
